version: '3'
services:
    build:
        build:
            context: ./
            dockerfile: Dockerfile
        image: maven:3.8.1
        working_dir: /app
        volumes:
            - .:/app
        ports: 
            - 8080:8080
        command: mvn clean spring-boot:run