version: '3.8'
services:
  ci: &defaults
    build:
      context: ./
      dockerfile: Dockerfile
    image: maven:3.8.1
    working_dir: /app
    volumes:
      - .:/app
    ports: 
        - 8080:8080
    command: mvn clean package

  app:
    <<: *defaults
    command: java -jar /app/app.jar
