site_name: "template-java"
site_description: "Main documentation for Backstage features and platform APIs"
repo_url: https://github.com/devxp-tech/template-java
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: "docs/index.md"
